// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackManagement.Infrastructure.Persistence;

#nullable disable

namespace TrackManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackManagement.Domain.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Egypt",
                            Email = "amr@music.com",
                            Name = "Amr Diab"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Egypt",
                            Email = "angham@music.com",
                            Name = "Angham"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Egypt",
                            Email = "info@cairokee.com",
                            Name = "Cairokee"
                        });
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.DSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dsps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "YouTube Music"
                        });
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Isrc")
                        .IsUnique();

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Pop",
                            Isrc = "EGX000000001",
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Nour El Ain"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Genre = "Pop",
                            Isrc = "EGX000000002",
                            ReleaseDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Tamally Maak"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Genre = "Rock",
                            Isrc = "EGX000000003",
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Sot El Horeya"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 1,
                            Genre = "Pop",
                            Isrc = "EGX000000004",
                            ReleaseDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Ya Ana Ya La"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            Genre = "Pop",
                            Isrc = "EGX000000005",
                            ReleaseDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Sidi Wesalak"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            Genre = "Rock",
                            Isrc = "EGX000000006",
                            ReleaseDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Khatam Solaiman"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 2,
                            Genre = "Classical",
                            Isrc = "EGX000000007",
                            ReleaseDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Omri Kabeer"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 3,
                            Genre = "Rock",
                            Isrc = "EGX000000008",
                            ReleaseDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Basrah W Ahooh"
                        });
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.TrackDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DspId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DspId");

                    b.HasIndex("TrackId", "DspId")
                        .IsUnique();

                    b.ToTable("TrackDistributions");
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.Track", b =>
                {
                    b.HasOne("TrackManagement.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.TrackDistribution", b =>
                {
                    b.HasOne("TrackManagement.Domain.Entities.DSP", "Dsp")
                        .WithMany("Distributions")
                        .HasForeignKey("DspId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackManagement.Domain.Entities.Track", "Track")
                        .WithMany("Distributions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dsp");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.DSP", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("TrackManagement.Domain.Entities.Track", b =>
                {
                    b.Navigation("Distributions");
                });
#pragma warning restore 612, 618
        }
    }
}
